<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MistwareUtils.csproj" />
  </ItemGroup>

 <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>MistwareUtilsTest</AssemblyName>
  </PropertyGroup>

</Project>
